quality gate added

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -52,7 +52,19 @@ stages:
           dotnet sonarscanner end \
             /d:sonar.token="$(SONAR_TOKEN)"
         displayName: SonarQube scan backend
-    
+      
+      - script: |
+          sleep 10
+
+          STATUS=$(curl -s -u $(SONAR_TOKEN): "$(SONAR_HOST_URL)/api/qualitygates/project_status?projectKey=three-tier-backend" | jq -r '.projectStatus.status')
+
+          echo "Quality Gate Status: $STATUS"
+
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate Failed"
+            exit 1
+          fi
+        displayName: Enforce Sonar Quality Gate
 
       - task: Docker@2
         displayName: Build backend image
